name: WebRTC Data Channel Interoperability Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [datachannel-test-command]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job Description: Performs the Data Channel Test between each combination of the client and server for each library.
  interop-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["libdatachannel", "sipsorcery", "werift"]
        client: ["libdatachannel", "sipsorcery", "werift"]
    services:
      echo-test-server:
        image: ghcr.io/sipsorcery/${{ matrix.server }}-webrtc-echo
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        #ports:
        #  - 8080:8080
        options: "--name echo-server"

    steps:
      - name: Set up result array
        run: echo "RESULTS=[]" >> $GITHUB_ENV
      - name: Data Channel test for server ${{ matrix.server }} and ${{ matrix.client }} client
        id: check_connection
        run: |
          docker run --entrypoint "/client.sh" --network ${{ job.container.network }} ghcr.io/sipsorcery/${{ matrix.client }}-webrtc-echo "-s http://echo-server:8080/offer -t 1"
          result=$?
          echo "Check connection for ${{ matrix.server }} server and ${{ matrix.client }} client result $result."
          echo "::set-output name=TEST_RESULT::$result"
        continue-on-error: true
      - name: Record result
        run: |
          echo "Result for ${{ matrix.server }} server and ${{ matrix.client }} client, outcome ${{ steps.check_connection.outcome }}, result ${{ steps.check_connection.outputs.TEST_RESULT }}."
          # echo "${{ matrix.server }},${{ matrix.client }},${{ steps.check_connection.outputs.TEST_RESULT }}" >> ${{ matrix.server }}_${{ matrix.client }}_result.csv
          # Append the result to the environment variable
          echo "RESULTS+=['${{ matrix.server }}','${{ matrix.client }}','${{ steps.check_connection.outputs.TEST_RESULT }}']" >> $GITHUB_ENV
          echo "GITHUB_ENV=${{ GITHUB_ENV }}"
          echo "RESULTS=${{ RESULTS ||"
          echo "env.RESULTS=${{ env.RESULTS }}"

  # Job Description: Collates the results of the interop tests into a mark down table.
  collate:
    runs-on: ubuntu-latest
    needs: [interop-tests]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testresults
      - name: Create results file from environment variable
        run: |
          echo "Collating results..."
          echo "| Server | Client | Test Result |" > DataChannel_Echo_test_results.md
          echo "|--------|--------|-------------|" >> DataChannel_Echo_test_results.md
          for result in ${{ env.RESULTS }}; do
            echo "| ${result[0]} | ${result[1]} | ${result[2]} |" >> DataChannel_Echo_test_results.md
          done
          cat DataChannel_Echo_test_results.md
      - name: Commit the results to the git repository
        if: github.event_name != 'pull_request'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          #git add DataChannel_Echo_test_results.md DataChannel_Echo_test_results.png
          #git commit DataChannel_Echo_test_results.md DataChannel_Echo_test_results.png -m "Automated data channel echo test results."
          #git add DataChannel_Echo_test_results.md
          git commit DataChannel_Echo_test_results.md -m "Automated data channel echo test results."
          git push
